### ISSUE TITLE
PLUGIN_EMAIL not used? Should it be removed as an option to the rule?

### ISSUE THREAD

**Issue by FlayaN** [Starfield-Reverse-Engineering/commonlibsf-xrepo#1]
https://github.com/Starfield-Reverse-Engineering/commonlibsf-xrepo/blob/2261e8501369f27ada3bd45c15c615efe9e0a31b/packages/c/commonlibsf/rules/plugin.lua#L7

https://github.com/Starfield-Reverse-Engineering/commonlibsf-xrepo/blob/2261e8501369f27ada3bd45c15c615efe9e0a31b/packages/c/commonlibsf/rules/plugin.lua#L84

**Comment by qudix** [comment]
I just left it in for future potential use. It doesn't really cost anything to leave it as is.

**Comment by FlayaN** [comment]
Ah ok, just thought it would be clearer to not have unused stuff. People might be curious why you should pass in email. Minimize the stuff they have to look up, maybe remove from the example project at least until it's used then?

**Comment by qudix** [comment]
Well if I remove it people are unlikely to populate it, which means if it gets used in the future their plugins wont contribute that info automatically.

**Comment by FlayaN** [comment]
Ah gotcha
